### ISSUE TITLE
Modify dev build to serve from / instead of /public

### ISSUE THREAD

**Issue by osteele** [olinlibrary/abe-web#106]
The dev branch of abe-web responds to <http://localhost:8080> with `Cannot GET /`.

This happens consistently on Mackenzie's machine. On my machine, it’s 100% reproducible with commit #984c3dd "Integrated webpack-dev-server with server.js to avoid duplicate index.html files", and a few later commits that I spot-checked. It does not happen with the preceding commit #805118b "Added lots of comments. Cleaned up code a little bit."

Adding back the [index.html](https://raw.githubusercontent.com/olinlibrary/abe-web/805118b8ee8d5d4680a23e4a06349574d4de8513/index.html) file deleted in commit #805118b  appears to fix the issue.

**Comment by frackleton** [comment]
update again, user needs to redirect to http://localhost:8080/public/ and then click on the olin logo in the top right hand portion of the site. 

the webpack dev server still runs at http://localhost:8080/, unsure if there's a way to update this so that it also directs users to http://localhost:8080/public/

**Comment by osteele** [comment]
I've updated the issue title.

The change below, that adds `devServer.contentBase` to the webdev config, causes <http://localhost:8080/> to serve the home page. This also removes the need to click on the Olin logo. (Probably the app is testing whether its route is `/` before redirecting to `/calendar/`.) However, the CSS is broken because the HTML links to <http://localhost:8080/public/css/app.css> (which in this configuration is served from <http://localhost:8080/css/app.css>) and <http://localhost:8080/node_modules/input-moment/dist/input-moment.css> (which I can't find).

There's another config property `devServer.publicPath` that may be relevant. Also `devServer.proxy` might be useful.

```
 diff --git a/webpack.config.js b/webpack.config.js
 --- a/webpack.config.js
 +++ b/webpack.config.js
 @@ -22,6 +22,7 @@ var config = {
          ]
      },
      devServer: {
 +        contentBase: './public',
          historyApiFallback: true
      },
      resolve: {
```

**Comment by osteele** [comment]
The following change appears to make the web available at `/`, and remove the need to then click on the logo to get things working. I'll commit this together with an update to the README once I'm able to create a calendar event. (Not being able to create a calendar event is independent of this change, but I don't want to commit on top of possibly broken code, or when I can't test everything.)

```
diff --git a/webpack.config.js b/webpack.config.js
 --- a/webpack.config.js
 +++ b/webpack.config.js
 @@ -22,6 +22,7 @@ var config = {
          ]
      },
      devServer: {
 +        contentBase: ['./public', '.'],
          historyApiFallback: true
      },
      resolve: {
```

**Comment by kylecombes** [comment]
The reason `index.html` was moved was because if you have an `index.html` file in `/` then it gets served up on Heroku, which is not what we want. I managed to get around that issue for another project, but this is a more elegant solution.
