### ISSUE TITLE
User can create an event with no label

### ISSUE THREAD

**Issue by osteele** [olinlibrary/abe-web#109]
Create an event. Don't give it a label. Return to the calendar view. The event is invisible. On production (where there is not a “unlabled” tag), there is no way to view it.

Recommended fix:
* [ ] The create event view doesn't validate if no label is selected.
* [ ] The edit event view doesn't validate if no label is selected.

**Comment by kylecombes** [comment]
@frackleton can you incorporate this in your work on `add-edit-event.jsx`?
