### ISSUE TITLE
User can create an event that isn't visible once they return to the calendar view

### ISSUE THREAD

**Issue by osteele** [olinlibrary/abe-web#110]
To reproduce:
* De-select a label, for example “academic”.
* Add an event that doesn't include this label

The newly created event isn't visible once the user completes the task and is returned to the calendar.

Recommended solution: *one* of
1. If the user creates an event with no tags in common with the calendar view, a warning appears on the Add Event screen and/or when the user is returned to the calendar view.
2. If the user creates an event with no tags in common with the calendar view, the event's tags are selected when the user returns to the calendar view. Also a message is displayed explaining that this has happened.
3. If the user tries to create an event with no tags in common with the calendar view, the event doesn't validate. The validation error explains the issue, and lists the tags that the user must select from.

Similarly for editing an event.

**Comment by kylecombes** [comment]
This was resolved by #161.
