### ISSUE TITLE
Production isn't picking up changes to ABE_URL

### ISSUE THREAD

**Issue by osteele** [olinlibrary/abe-web#124]
I'm trying to set production to use https://abe-api-prod.herokuapp.com as an API server (as a workaround for olinlibrary/ABE#143 while we wait for a support response or figure out another solution).

* Set the abe-api-prod app's ABE_URL to https://abe-api-prod.herokuapp.com.
* For good measure, restart dynos. (Changing the config is supposed to do this anyway.)
* Visit http://events.olin.edu or http://events.olin.edu.
* Expected:
  * The page source includes `window.abe_url = 'https://abe-api-prod.herokuapp.com'`.
  * The app requests events and labels from https://abe-api-prod.herokuapp.com.
  * The GUI shows events

Actual:
  * Two error alerts appear: “There was an error while fetching events!” and “TypeError: An SSL error has occurred and a secure connection to the server cannot be made.”
  * Inspection of the web console reveals that the app is requesting https://abe.olin.build/events/?start=2018-3-31&end=2018-5-12 and https://abe.olin.build/labels/.
  * Page source shows `window.abe_url = 'https://abe.olin.build'`.

**Comment by osteele** [comment]
I've verified that the environment variable is correct in the app settings and in the dyno environment:

```bash
$ heroku config:get -a abe-web ABE_URL
https://abe-api-prod.herokuapp.com
$ heroku run bash -a abe-web
Running bash on ⬢ abe-web... up, run.3299 (Hobby)
~ $ printenv ABE_URL
https://abe-api-prod.herokuapp.com
```

**Comment by osteele** [comment]
It looks like prod is using the `index.html` file, rather than the constructed string that interpolates the value of `ABE_URL`. `yarn webpack:deploy` doesn't create an `index.html` in the webpack output path (`public/build`), and the served file begins with:

```
<!DOCTYPE html>
<!-- NOTE: This file is used during development ONLY. On production, index.html.js is used in conjunction with Express.
     Any changes made to this file should be made to the HTML in index.html.js as well. -→
```

**Comment by osteele** [comment]
I'm looking at using the webpack environment plugin to expose the build-time environment variable directly to the js.

**Comment by kylecombes** [comment]
Yeah, it appears to be serving the static `index.html`. One way to fix this is to simply move that file to a different directory (e.g. `public`), as has been done on `dev`, so that `/` gets handled by the Node Express server.
