### ISSUE TITLE
Git URL dependencies should specify commit-ish

### ISSUE THREAD

**Issue by osteele** [olinlibrary/abe-web#131]
For reproducible builds, git URL dependencies should [specify the commit-ish](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies).

This could also fix “I'm having trouble getting Heroku to update its copy of the `ultra-responsive-calendar module`” in #120.

**Comment by osteele** [comment]
The commits are store in `yarn.lock`, so this isn't actually necessary for reproducible builds. An alternative to editing the new commit `package.json` is to use `yarn upgradeInteractive` to upgrade just the lock.

**Comment by kylecombes** [comment]
I might publish `ultra-responsive-calendar` to npm...

**Comment by osteele** [comment]
Closing. For now at least, `yarn.lock` is a better solution.
