### ISSUE TITLE
New events don't show up

### ISSUE THREAD

**Issue by osteele** [olinlibrary/abe-web#156]
To reproduce:
1. Visit the calendar
2. Select All Labels
3. Click Add Event
4. Enter "an event" as the title, and select at least one label
5. Click Add Event. The system returns to the calendar view.

Expected: The calendar view includes the new event.

Actual: The new event is not visible until the page is refreshed.

The reverse bug also appears when an event is deleted. It is still displayed on return to the calendar page. I'm writing this up here too instead of creating a separate issue because I suspect they have the same underlying cause. Once the new events is fixed, event deletion should be tested too, and written up if it is still extent.

**Comment by kylecombes** [comment]
This should probably be solved by refetching all event data from the server, since it could involve nasty recurrence creation/modification/deletion.
