### ISSUE TITLE
Display unauthenticated error message to user if server returns 401 unauthorized

### ISSUE THREAD

**Issue by kylecombes** [olinlibrary/abe-web#34]
Backend will be handling "authentication," but we need to display a descriptive error message if someone tries to make a change while not on the Olin network.

### Steps to ameliorate 401:
  * Be sure you're on **OLIN**, not OLIN-GUEST
  * If off-campus, connect with VPN

**Comment by kylecombes** [comment]
Should maybe integrate with #54

**Comment by osteele** [comment]
Replaced by #179 and #217.
