### ISSUE TITLE
Resize FullCalendar views to fill screens

### ISSUE THREAD

**Issue by newsch** [olinlibrary/abe-web#41]
Right now the month view on mobile doesn't take advantage of the portrait aspect ratio, so a lot of information is lost.
I've found a bit of info on resizing fullcalendar:
- https://stackoverflow.com/questions/5191616/how-can-i-auto-fit-fullcalendar-into-a-specified-div-space
- https://stackoverflow.com/questions/9982045/fullcalendar-resize-calendar-on-window-resize

**Comment by kylecombes** [comment]
Unless this is a quick fix, @audreywl, I think we should just wait until my [ultra-responsive-calendar](https://github.com/kylecombes/ultra-responsive-calendar) is in beta.

**Comment by kylecombes** [comment]
Ditching FullCalendar, so no longer relevant.
