### ISSUE TITLE
Better Flow for Subscribing to ICS feed

### ISSUE THREAD

**Issue by audreywl** [olinlibrary/abe-web#64]
Right now we just tell people to go into their calendar application settings and subscribe, but people who aren't experienced at navigating their settings will have difficulty with that and may not just not subscribe.

If we use webcal:// instead of http:// for the link to the calendar (which already works with the backend like it is), Outlook will automatically open and subscribe to the calendar. There isn't a similar URI handler in Google Calendar, which leads me to think we should have two buttons - one to subscribe in outlook that just opens the webcal link and one for Google Calendar that steps you through the process of subscribing.

**Comment by kylecombes** [comment]
Partially ameliorated in 3212d1773bd6abf9e8b6bd901045317f9605aeb1
