### ISSUE TITLE
Edit Occurrence from calendar broken

### ISSUE THREAD

**Issue by audreywl** [olinlibrary/abe-web#87]
Looks like the links on the calendar for Edit Occurrence (in the tooltip for a recurring event) are no longer formatted correctly - they point to a view instead of an edit page, e.g.

http://events.olin.build/view/59774841e44d46221dfd0fa8/1501632000000
vs.
http://events.olin.build/edit/59774841e44d46221dfd0fa8/1501632000000

The process of editing still goes fine if you can get to the right page, the link is just wrong.

**Comment by audreywl** [comment]
I take it back the process of editing does not go fine, it's all broken and idk if it's us or ABE.

**Comment by kylecombes** [comment]
@audreywl I can't determine if this is on our end or on the backend. The logs for the backend are revealing nothing, so I have no insight into what's causing the problem.

@Elepert or @newsch, should the URL for a PUT request for a recurring event be in the form of `/events/<sid>` or `/events/<sid>/<rec_id>`? Right now we're sending it as the former, but it looks like we've been doing that for a while...

**Comment by kylecombes** [comment]
Scratch that, I was looking at the wrong log. This is what it says:

    File "/app/abe/resource_models/event_resources.py", line 138, in put
    |     received_data['rec_id'] = dateutil.parser.parse(str(received_data['rec_id']))
    | NameError: name 'dateutil' is not defined

**Comment by kylecombes** [comment]
Resolved in olinlibrary/ABE#bbb60d1
