### ISSUE TITLE
Events with no location export with location = “none” string

### ISSUE THREAD

**Issue by osteele** [olinlibrary/abe-web#93]
To reproduce:
* Open <http://events.olin.build/>
* Copy ICS link to Clipboard
* Open <https://calendar.google.com/>
* “Add by URL” the ICS link

Expected:
* Events with no location will not display location text in the Google Calendar day, week, or month views; e.g. “Labor Day”

Actual:
* Events with no location display “none” as the location; e.g. “Labor Day – none”. See screenshots.

# Screen shots

## ABE event
<img width="531" alt="screenshot of safari 8-29-17 8-21-13 am" src="https://user-images.githubusercontent.com/674/29820924-1deb3dc8-8c94-11e7-83fc-0c7aa637422c.png">

## Google Calendar month view
<img width="512" alt="screenshot of safari 8-29-17 8-22-51 am" src="https://user-images.githubusercontent.com/674/29820942-3028c320-8c94-11e7-81ab-c9c2b8adeedc.png">

## Google Calendar event detail
<img width="261" alt="screenshot of safari 8-29-17 8-23-13 am" src="https://user-images.githubusercontent.com/674/29820892-01f85e98-8c94-11e7-96ef-e5ffa204d3d5.png">

**Comment by kylecombes** [comment]
This is a backend issue more than a frontend issue (issue opened), but I suppose we could make sure we don't send location if it's empty. Currently it looks like we'll send an empty string.

**Comment by kylecombes** [comment]
We should probably not have anything for `location` in the event data that goes to the server if the location field is blank. Then we'll need to make sure the backend knows not to export `None` (which looks like a Python artifact) when generating an ICS feed.

**Comment by kylecombes** [comment]
You'll want to use the Firefox developer tools to watch what data is being sent back and forth to the server.
