### ISSUE TITLE
Seconds Causing Rounding Errors in Subscribed Calendars

### ISSUE THREAD

**Issue by audreywl** [olinlibrary/abe-web#95]
When we create an event, we start off with the current date/time, and then round to the nearest convenient minute interval, but we don't ever touch seconds. Outlook, and presumably other calendar applications, round those seconds to the closest minute, while we just truncate when we display. This causes some events to appear shifted by a minute on external calendar applications. It's particularly bad for All-Day events, which we set with the [moment.js "end of" function](https://momentjs.com/docs/#/manipulating/end-of/) to happen at the last possible second on the last day, so they're always rounded to the next day, causing the behavior described in https://github.com/olinlibrary/ABE/issues/108. To fix this behavior, we not only need to begin modifying seconds to 00 when we create events (because we're presumably not using second resolution anyway), but work with ABE to modify events already in the database.

**Comment by kylecombes** [comment]
I think the backend should be able to handle this without us. It should be able to drop the seconds off a time before saving it to the db.

**Comment by kylecombes** [comment]
After a discussion with the backend team on Monday, we decided that the backend should not chop off seconds. While this doesn't necessarily make sense for a calendar (what event needs seconds granularity?), we don't want to restrict uses of ABE to *only* being used as a traditional calendar. Events, broadly speaking, may have seconds granularity.
